# Generated by Django 5.2 on 2025-04-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_navbarcategory_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='navbar_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='medapp.navbarcategory'),
        ),
    ]
