# Generated by Django 5.2 on 2025-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0005_subcategory_navbar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/navbar_categories/categories/'),
        ),
        migrations.AlterField(
            model_name='navbarcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/navbar_categories/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/navbar_categories/categories/subcategories/'),
        ),
    ]
