# Generated by Django 5.2 on 2025-04-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0006_alter_category_image_alter_navbarcategory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('requires_prescription', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule'), ('injection', 'Injection')], default='tablet', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='medapp.category')),
                ('navbar_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='medapp.navbarcategory')),
                ('sub_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='medapp.subcategory')),
            ],
        ),
    ]
