# Generated by Django 5.2 on 2025-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0009_rename_image_products_image_2_products_image_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Indian Rupees (INR)', max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('requires_prescription', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule'), ('injection', 'Injection')], default='tablet', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='medapp.category')),
                ('navbar_categories', models.ManyToManyField(blank=True, related_name='products', to='medapp.navbarcategory')),
                ('sub_categories', models.ManyToManyField(blank=True, related_name='products', to='medapp.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
