# Generated by Django 5.2 on 2025-04-08 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0012_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('qualifications', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('available_days', models.CharField(help_text='e.g. Mon-Wed-Fri', max_length=100)),
                ('available_time', models.CharField(help_text='e.g. 10:00 AM - 1:00 PM', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('is_active', models.BooleanField(default=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
