# Generated by Django 5.2 on 2025-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0014_doctor_date_of_birth_doctor_gender_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
