# Generated by Django 5.2 on 2025-04-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0015_alter_doctor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='street_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
