# Generated by Django 5.2 on 2025-04-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0016_remove_patient_address_patient_city_patient_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='street_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
