# Generated by Django 5.2 on 2025-04-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0019_patient_address_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text="Patient's email address", max_length=254, null=True),
        ),
    ]
