# Generated by Django 5.2 on 2025-04-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0021_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_id',
            new_name='upi_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
