# Generated by Django 5.2 on 2025-04-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0022_rename_razorpay_payment_id_order_upi_id_and_more'),
    ]

    operations = [
    ]
