# Generated by Django 5.2 on 2025-04-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0023_auto_20250409_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
