# Generated by Django 5.2 on 2025-04-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0026_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
