# Generated by Django 5.2 on 2025-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0029_videochatrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochatrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videochatrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
