# Generated by Django 5.2 on 2025-04-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0030_videochatrequest_latitude_videochatrequest_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochatrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videochatrequest',
            name='video_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
