# Generated by Django 5.2 on 2025-04-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0031_videochatrequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochatrequest',
            name='chat_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videochatrequest',
            name='chat_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videochatrequest',
            name='chat_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videochatrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('waiting_for_response', 'Waiting for Response'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
