# Generated by Django 5.2 on 2025-04-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0032_videochatrequest_chat_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochatrequest',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
